### PR TITLE
Stage react api

### PR DESCRIPTION
**Pull request by blinn26**
code review

### CODE REVIEW

**Comment by blinn26** [comment]
deploy

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for submitting this project for review - you've done a lot of work. I especially like your semantic and BEM implementing - very impressive! I left comments below, so you can fix them to improve your project and get more points. Good luck✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * All pages have many mismatches with the design - incorrect sizes, spaces, text properties and colors - you need to check all items one by one and compare it with the design page for 320px, 768px and 1440px screen resolutions - the project should look similar with the mockup
    * `about` block shouldn't have `cursor: pointer` style, it's a property for interactive elements like links or buttons - using it for non-interactive blocks may confuse the user
    * All items in the footer navigation should have hover state and pointer cursor
    * Header navigation should be placed in a row on 768 viewport (mobile navigation should be used only for 320px breakpoint)
    * Mobile navigation is broken on `saved-news` page it looks and works incorrectly
    * Content of the popup window shouldn't extend outside the popup window
    * `modal__error-message` should be placed in a row inside popup window
    * `search-form__field` shouldn't have pointer cursor, only search button should
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page scrolls horizontally on 320px - 336px screen resolutions on both pages
    * `footer__copyright` looks too small on 767px - 900px screen resolutions
    * The page breaks on 767px screen resolution
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * `header_image`, `navigation_transparent`, `navigation_light` classes should be key-value modifiers instead of boolean
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * `news-container`, `saved-news-header` and `news-card-list-wrapper` should be sections
    * `modal__alternative-action` should be a link or a button
    * Please use `main` tag on `saved-news` page
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [ ] An `images`
      * Please move `images` folder outside the `components` folder
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * All buttons and links should have pointer cursor
    * You need to make sure that all buttons and links have hover state (and some buttons - marked or clicked state) according to the mockup
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using `@font-face`.
    * Fonts should be connected locally using separate css file with `@font-face` rules
- [ ]  The icons are exported in SVG format.
    * Not all icons are used in `svg` format
- [ ]  Form elements should be highlighted when focused.
    * `modal__alternative` and `search-form__button` should be highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
     * `news-card__source` doesn't have an alternative font
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 52

**Comment by blinn26** [comment]
pull/2

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for the corrections, your project looks much better (especially adaptive layout) - good job! I left several comments below, you should fix them to get more points. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * The project shouldn't have only black and white colors - all necessary colors should be used according to the mockup
    * Incorrect text properties of `navigation__user`
    * Big distance between `header__title` and `header__description` on 1440 viewport
    * `search-form__input` should have bigger height and there should be no black vertical spaces
    * Incorrect font-weight of `search-results-title`
    * Incorrect text properties and spaces of all items inside `news-card`
    * Incorrect width of `about` section and width of text container inside the block
    * You should check and fix all text properties, sizes and spaces of the page content on 768 and 320 viewports
    * Incorrect width, text properties and spaces inside `saved-news-header` on 1440px, 768px and 320px screen resolutions
    * Incorrect size (width and height) of the popup window in 320px, 768px and 1440px screen resolutions
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * The project gets an error if I clicked on `news-card__save-clicked` button
    * sign in popup should be opened when `sign` in button has been clicked (now clicking on sign in button in header provokes sign up popup opening)
- [ ]  Classes are named according to BEM specifications.
    * `header_image`, `navigation_transparent`, `navigation_light` classes should be key-value modifiers instead of boolean
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * `news-container`, `saved-news-header` and `news-card-list-wrapper` should be sections
    * `modal__alternative-action` should be a link or a button
    * Please use main tag on `saved-news` page
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `search-form__button` should have hover and clicked state
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `modal__alternative` and `search-form__button` should be highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * `news-card__source` doesn't have an alternative font
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 58

**Comment by FiLLa-FaS** [comment]
Hi! Your project is almost finished, I left several small comments below, please fix them to improve your project and get more points. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * `Preloader` component looks different than the mockup on all screen resolutions
    * Incorrect text properties of `navigation__user`
    * `news-card__title` shouldn't have underlined style
    * `main__show-more-button` and `modal__button-submit` shouldn't have border
    * You should check and fix all text properties, sizes and spaces of the page content on 768 and 320 viewports, most of them don't correspond the design https://disk.yandex.ru/i/ICfiec3c60ZXTg https://disk.yandex.ru/d/7OhEDlvNRr7cpA https://disk.yandex.ru/i/Rx2qg8wumtidwg (all the screenshots are from 768px and you should find and fix all the mismatches on 320 viewport by yourself)
    * Incorrect width, text properties and spaces inside `saved-news-header` on 1440px, 768px and 320px screen resolutions
    * Incorrect size (width and height) of the popup window on 320px screen resolution
    * Popup window should be centered horizontally on all screen resolutions
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * `header_image`, `navigation_transparent`, `navigation_light` classes should be key-value modifiers instead of boolean
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * `news-container`, `saved-news-header` and `news-card-list-wrapper` should be sections, and `about__image-container`  shouldn't be sections
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `news-card__save-clicked` should have blue background color
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
    * `news-card__source` doesn't have an alternative font
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 75

**Comment by FiLLa-FaS** [comment]
Hi! Your project has been improved a lot, I'm impressed with the work you've done on mobile and tablet breakpoints. I left several comments below, please fix them to get more points and improve the project. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Big distance between `news-container` and `search-results-title`, `main__show-more-button` and `about` on 768, 320 viewports
    * Incorrect distance between `header__title` and `header__description` on 320 viewport
    * Incorrect width of `search-form` on 320 viewport
    * Incorrect distance between `news-container` and `search-results-title`, `search-results-title` and `news-card-container` on 320 viewport
    * Incorrect text properties of `about__text` on 320 viewport
    * Footer looks incorrectly on 320 viewport
    * You should check width, text properties and spaces of `saved-news__container` and all its content on all screen resolutions
    * Incorrect size (width and height) of the popup window on 320px screen resolution
    * Popup window should be centered horizontally and close button shouldn't extend outside the screen on all screen resolutions
    * Incorrect size (width and height) of the popup window on 320px screen resolution
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
    * `header_image`, `navigation_transparent`, `navigation_light` classes should be key-value modifiers instead of boolean https://en.bem.info/methodology/quick-start/#key-value
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * There should be only 1 `main` tag on the page (it should contain all sections between header and footer). Now each page has 3 nesting `main` tags
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Not all `font-family` styles throughout the project have alternative font and generic font-family
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 77

**Comment by FiLLa-FaS** [comment]
Hi! You've got more than 80 points, so I'm glad to approve it. Btw you still can fix the rest issues below to improve the user experience. Congratulations and good luck on the next stage!🚀

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Big distance between `news-container` and `search-results-title`, `main__show-more-button` and `about` on 768, 320 viewports
    * Incorrect distance between `header__title` and `header__description` on 320 viewport
    * Incorrect width and location of `search-form` on 320 viewport (items should be centered horizontally)
    * Incorrect distance between `news-container` and `search-results-title`, `search-results-title` and `news-card-container` on 320 viewport
    * Incorrect size (width and height) of the popup window on 320px screen resolution
    * Popup window should be centered horizontally and close button shouldn't extend outside the screen on all screen resolutions
    * You should check width, text properties and spaces of `saved-news__container` and all its content on all screen resolutions
    * `saved-news` page scrolls horizontally on 321px - 741px screen resolutions
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 87

**Pull request merged**
